from .auth import router as auth_router
from .bot_settings import router as bot_settings_router
from .categories import router as categories_router
from .dashboard import router as dashboard_router
from .leads import router as leads_router
from .notifications import router as notifications_router
from .products import router as products_router
from .promotions import router as promotions_router
from .roles import router as roles_router
from .subcategories import router as subcategories_router
from .upload import router as upload_router
from .users import router as users_router
