from .bot_admin import router as bot_admin_router
from .bot_subscribers import router as bot_subscribers_router
from .bot_settings import router as bot_settings_router
from .categories import router as categories_router
from .leads import router as leads_router
from .products import router as products_router
from .promotions import router as promotions_router
from .subcategories import router as subcategories_router
from .telegram import router as telegram_router
